FROM node:22.11.0-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm ci 
COPY . .
RUN npm run build

FROM node:22.11.0-alpine as runtime
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY package*.json ./
RUN npm install --production --ignore-scripts
RUN npm rebuild bcrypt 


EXPOSE 8080
CMD ["npm", "run", "start"]
