services:
  database:
    image: postgres
    restart: always
    container_name: url-shortener-database
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - url_shortener_db:/var/lib/postgresql/data
  api:
    build: .
    restart: always
    container_name: url-shortener-api
    ports:
      - 3000:${PORT}
      - 9229:9229
    environment:
      - NODE_ENV=DEVELOPMENT
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  url_shortener_db:
    driver: local
