services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    container_name: url-shortener-api
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=PRODUCTION
